### ISSUE TITLE
sudo npm run build fails

### ISSUE THREAD

**Issue by tonypius** [neo4j-labs/neoconverse#1]
sudo npm run build fails when I run it. 
<img width="1022" alt="Screenshot 2024-05-14 at 5 34 55 PM" src="https://github.com/neo4j-labs/neoconverse/assets/3880829/9f9e9409-43a0-49d4-919b-d1f78536f192">

It fails on an syntax issue.

**Comment by Ayo-faks** [comment]
Run without sudo

**Comment by tonypius** [comment]
Same error with and without sudo

**Comment by kumarss20** [comment]
@tonypius This seems to be an issue with the node version, you might want to upgrade to node 15 + and try again 

References

https://stackoverflow.com/questions/74707066/nextjs-unexpected-token

https://github.com/vercel/next.js/discussions/49923

**Comment by tonypius** [comment]
That seemed to have fixed the issue. Thanks.
